
CompileFlags:
  Add:
    - -Wno-char-subscripts

Diagnostics:
  Suppress:
    - cppcoreguidelines-init-variables
    - cert-err33-c
    - llvmlibc-restrict-system-libc-headers
    - concurrency-mt-unsafe
    - altera-*
    - bugprone-assignment-in-if-condition
    - hicpp-signed-bitwise
    - bugprone-narrowing-conversions
    - c99-designator
    - bugprone-reserved-identifier
    - cert-dcl51-cpp
    - initializer-overrides
    - hicpp-avoid-c-arrays
    - sign-compare
    - sign-conversion
    - implicit-int-conversion
    - shorten-64-to-32
    - incompatible-pointer-types-discards-qualifiers
    - pointer-sign
    - cast-align
    - cast-qual
    - old-style-cast
    - zero-as-null-pointer-constant
    - unused-parameter
    - padded
    - switch-enum
    - covered-switch-default
    - declaration-after-statement
    - readability-function-cognitive-complexity

  ClangTidy:
    Remove:
      - llvmlibc-restrict-system-libc-headers
      - llvmlibc-*
      - modernize-*
      - readability-identifier-naming
      - cppcoreguidelines-*
      - google-*
      - llvm-*
      - altera-*
      - fuchsia-*
      - hicpp-*
      - cert-*
      - readability-magic-numbers
      - readability-isolate-declaration
      - readability-identifier-naming
      - readability-function-cognitive-complexity
