font_family      JetBrainsMono NFM
bold_font        JetBrainsMono NFM Bold
italic_font      JetBrainsMono NFM Italic
bold_italic_font JetBrainsMono NFM Bold Italic
font_size        8.0

foreground       #FAF0E6
background       #251a34

cursor           #fdfdaf
cursor_text_color #251a34

color0  #000000
color1  #db4b4b
color2  #9ece6a
color3  #ffdd00
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6

color8  #565f89
color9  #f7768e
color10 #73daca
color11 #ffee00
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

copy_on_select clipboard

map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0

map ctrl+shift+g show_last_command_output

map ctrl+shift+y copy_last_command_output

mouse_map ctrl+middle release ungrabbed,grabbed paste_selection
mouse_map ctrl+middle press grabbed discard_event
