#!/bin/bash

main() {
    local pfx="${1?missing prefix}"
    local base="${2:-origin/master}"

    case "$base" in
    *[!0-9]*) ;;
    *) base="HEAD~${base}" ;;
    esac

    export REBASE_PFX="$pfx"

    git rebase "$base" --exec \
        'msg=$(git log -1 --format=%B); git commit --amend -m "[$REBASE_PFX] $msg"'
}

main "$@"
