#!/bin/bash

main() {
    xrandr --output HDMI-1 --mode 3840x2160 --rate 60
    #xrandr --output DP-1 --mode 3840x2160 --rate 240
    xrandr --output DP-3 --mode 3840x2160 --rate 240 --right-of HDMI-1
}

main "$@"
